// PacRipper command-stream memory analysis byte-value / command-stream dataflow integration
// Created by Jacob Hodgkins

#include "Decompiler.h"

#include <iomanip>
#include <map>
#include <set>
#include <sstream>

namespace pacripper {
namespace {
std::string h21(std::uint16_t v){std::ostringstream o;o<<std::uppercase<<std::hex<<std::setw(4)<<std::setfill('0')<<(unsigned)v;return o.str();}
std::string h821(std::uint8_t v){std::ostringstream o;o<<std::uppercase<<std::hex<<std::setw(2)<<std::setfill('0')<<(unsigned)v;return o.str();}
template<class T>std::string ids21(const std::set<T>&s,const char*p=""){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<p<<v;}o<<"}";return o.str();}
std::string pcs21(const std::set<std::uint16_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<"$"<<h21(v);}o<<"}";return o.str();}
std::string bytes21(const std::set<std::uint8_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<"$"<<h821(v);}o<<"}";return o.str();}
std::string domain21(const AddressLatticeValue&v){std::set<std::uint16_t>d;if(!RootContextAnalysis::completeFiniteDomain(v,d))return"unknown";std::ostringstream o;if(d.size()>64){o<<"{count="<<d.size()<<",min=$"<<h21(*d.begin())<<",max=$"<<h21(*d.rbegin())<<"}";return o.str();}return pcs21(d);}
}

void Decompiler::buildCommandStream(){
    commandStreamWriterAliases_.clear();commandStreamValueProofs_.clear();commandStreamCommandStreams_.clear();commandStreamAddressProofs_.clear();commandStreamClosureProvenance_.clear();commandStreamClosureBytes_.clear();stats_.commandStream={};
    if(!analyzer_)return;
    const auto&baseline=!memoryAliasClosureBytes_.empty()?memoryAliasClosureBytes_:rootContextClosureBytes_;commandStreamClosureBytes_=baseline;
    const auto result=CommandStreamAnalysis::analyze(*analyzer_,systemRootReachability_,memoryAliasWriterProofs_,memoryAliasWriterAliases_);
    commandStreamWriterAliases_=result.writerAliases;commandStreamValueProofs_=result.valueProofs;commandStreamCommandStreams_=result.commandStreams;commandStreamAddressProofs_=result.addressProofs;

    std::map<std::uint16_t,CommandStreamClosureProvenanceRecord>prov;
    for(const auto&p:commandStreamAddressProofs_){
        if(!CommandStreamAnalysis::semanticRomClosureEligible(p)) continue;
        std::set<std::uint16_t> d;
        if(!RootContextAnalysis::completeFiniteDomain(p.address,d)) continue;
        const bool exact=d.size()==1;
        for(auto a:d){if(a>=commandStreamClosureBytes_.size()||a>=baseline.size()||baseline[a].primary!=RomClosurePrimary::Unresolved)continue;auto&b=commandStreamClosureBytes_[a];if(exact)b.staticExactDataUse=true;else b.boundedConsumer=true;b.consumerPCs.insert(p.pc);b.primary=RomClosure::classify(b);auto&v=prov[a];v.address=a;v.exact=v.exact||exact;v.bounded=v.bounded||!exact;v.addressProofIds.insert(p.id);v.valueProofIds.insert(p.valueProofIds.begin(),p.valueProofIds.end());v.writerAliasRecordIds.insert(p.writerAliasRecordIds.begin(),p.writerAliasRecordIds.end());v.commandStreamRecordIds.insert(p.commandStreamRecordIds.begin(),p.commandStreamRecordIds.end());v.sourcePCs.insert(p.pc);v.sourcePCs.insert(p.proofPCs.begin(),p.proofPCs.end());if(!v.note.empty())v.note+="; ";v.note+=exact?"exact command-stream memory analysis finite ROM address":"bounded command-stream memory analysis finite command/lifecycle address";}
    }
    for(auto&kv:prov)commandStreamClosureProvenance_.push_back(kv.second);

    auto&st=stats_.commandStream;st.writerAliasInventories=commandStreamWriterAliases_.size();for(const auto&r:commandStreamWriterAliases_)if(r.complete)++st.completeWriterAliasInventories;st.valueProofs=commandStreamValueProofs_.size();for(const auto&p:commandStreamValueProofs_)if(p.accepted)++st.acceptedValueProofs;st.commandStreamRoots=commandStreamCommandStreams_.size();std::set<std::uint16_t>tokens,payloads,targets;for(const auto&r:commandStreamCommandStreams_){if(r.complete)++st.completeCommandStreams;if(r.hasCycle)++st.commandCycles;tokens.insert(r.tokenAddresses.begin(),r.tokenAddresses.end());payloads.insert(r.f0PayloadAddresses.begin(),r.f0PayloadAddresses.end());payloads.insert(r.f1PayloadAddresses.begin(),r.f1PayloadAddresses.end());payloads.insert(r.f2PayloadAddresses.begin(),r.f2PayloadAddresses.end());payloads.insert(r.f3PayloadAddresses.begin(),r.f3PayloadAddresses.end());payloads.insert(r.f4PayloadAddresses.begin(),r.f4PayloadAddresses.end());targets.insert(r.replacementTargets.begin(),r.replacementTargets.end());}st.commandTokenAddresses=tokens.size();st.commandPayloadAddresses=payloads.size();st.commandReplacementTargets=targets.size();st.addressProofs=commandStreamAddressProofs_.size();for(const auto&p:commandStreamAddressProofs_)if(p.accepted)++st.acceptedAddressProofs;st.inheritedBlockers=result.inheritedBlockerPCs.size();st.refinedInheritedBlockers=result.refinedInheritedBlockerPCs.size();st.remainingInheritedBlockers=result.remainingInheritedBlockerPCs.size();st.newlyRootedBlockers=result.newlyRootedBlockerPCs.size();st.refinedNewlyRootedBlockers=result.refinedNewlyRootedBlockerPCs.size();st.remainingNewlyRootedBlockers=result.remainingNewlyRootedBlockerPCs.size();st.totalRemainingBlockers=st.remainingInheritedBlockers+st.remainingNewlyRootedBlockers;st.closureProvenanceRecords=commandStreamClosureProvenance_.size();
    bool in=false;for(std::size_t i=0;i<commandStreamClosureBytes_.size();++i){const bool u=commandStreamClosureBytes_[i].primary==RomClosurePrimary::Unresolved;if(u){++st.unresolvedAfterCommandStream;if(!in){++st.residualSpansAfterCommandStream;in=true;}}else in=false;if(i<baseline.size()&&baseline[i].primary==RomClosurePrimary::Unresolved&&!u){if(commandStreamClosureBytes_[i].staticExactDataUse)++st.newlyExactExplainedBytes;else ++st.newlyBoundedExplainedBytes;}}st.newlyExplainedBytes=st.newlyExactExplainedBytes+st.newlyBoundedExplainedBytes;
}

std::vector<std::string> Decompiler::commandStreamWriterAliasLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper command-stream memory analysis exact-target writer alias inventories");o.push_back("inventories="+std::to_string(stats_.commandStream.writerAliasInventories)+" complete="+std::to_string(stats_.commandStream.completeWriterAliasInventories));for(const auto&r:commandStreamWriterAliases_)o.push_back("alias#"+std::to_string(r.id)+" targets="+pcs21(r.targetAddresses)+" complete="+(r.complete?"yes":"no")+" direct="+pcs21(r.directWriterPCs)+" indirect="+pcs21(r.indirectWriterPCs)+" unknown="+pcs21(r.unknownAliasWriterPCs)+" writer-proofs="+ids21(r.indirectWriterProofIds,"wproof#")+" :: "+r.note);return o;}
std::vector<std::string> Decompiler::commandStreamValueProofLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper command-stream memory analysis byte-value memory lattice proofs");o.push_back("proofs="+std::to_string(stats_.commandStream.valueProofs)+" accepted="+std::to_string(stats_.commandStream.acceptedValueProofs));for(const auto&p:commandStreamValueProofs_)o.push_back("value#"+std::to_string(p.id)+" "+p.name+" targets="+pcs21(p.targetAddresses)+" kind="+CommandStreamAnalysis::byteValueKindText(p.value.kind)+" values="+bytes21(p.value.values)+" unknown-alt="+(p.value.hasUnknownAlternative?"yes":"no")+" accepted="+(p.accepted?"yes":"no")+" aliases="+ids21(p.writerAliasRecordIds,"alias#")+" proof="+pcs21(p.proofPCs)+" :: "+p.note);return o;}
std::vector<std::string> Decompiler::commandStreamCommandStreamLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper command-stream memory analysis command-object stream graph");o.push_back("roots="+std::to_string(stats_.commandStream.commandStreamRoots)+" complete="+std::to_string(stats_.commandStream.completeCommandStreams)+" tokens="+std::to_string(stats_.commandStream.commandTokenAddresses)+" payloads="+std::to_string(stats_.commandStream.commandPayloadAddresses)+" replacement-targets="+std::to_string(stats_.commandStream.commandReplacementTargets)+" cycles="+std::to_string(stats_.commandStream.commandCycles));for(const auto&r:commandStreamCommandStreams_)o.push_back("stream#"+std::to_string(r.id)+" object=$"+h21(r.objectBase)+" selector="+std::to_string(r.selector)+" root=$"+h21(r.root)+" tokens="+std::to_string(r.tokenAddresses.size())+" F0-payload="+pcs21(r.f0PayloadAddresses)+" F1="+pcs21(r.f1PayloadAddresses)+" F2="+pcs21(r.f2PayloadAddresses)+" F3="+pcs21(r.f3PayloadAddresses)+" F4="+pcs21(r.f4PayloadAddresses)+" targets="+pcs21(r.replacementTargets)+" cycle="+(r.hasCycle?"yes":"no")+" complete="+(r.complete?"yes":"no")+" :: "+r.note);return o;}
std::vector<std::string> Decompiler::commandStreamAddressProofLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper command-stream memory analysis finite address proofs");o.push_back("proofs="+std::to_string(stats_.commandStream.addressProofs)+" accepted="+std::to_string(stats_.commandStream.acceptedAddressProofs)+" inherited-refined="+std::to_string(stats_.commandStream.refinedInheritedBlockers)+" new-root-refined="+std::to_string(stats_.commandStream.refinedNewlyRootedBlockers)+" remaining="+std::to_string(stats_.commandStream.totalRemainingBlockers));for(const auto&p:commandStreamAddressProofs_)o.push_back("proof#"+std::to_string(p.id)+" pc=$"+h21(p.pc)+" kind="+CommandStreamAnalysis::proofKindText(p.kind)+" class="+RootContextAnalysis::domainClassText(p.domainClass)+" domain="+domain21(p.address)+" accepted="+(p.accepted?"yes":"no")+" values="+ids21(p.valueProofIds,"value#")+" aliases="+ids21(p.writerAliasRecordIds,"alias#")+" streams="+ids21(p.commandStreamRecordIds,"stream#")+" :: "+p.note);return o;}
std::vector<std::string> Decompiler::commandStreamClosureLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper command-stream memory analysis residual consumer closure");o.push_back("new="+std::to_string(stats_.commandStream.newlyExplainedBytes)+" exact="+std::to_string(stats_.commandStream.newlyExactExplainedBytes)+" bounded="+std::to_string(stats_.commandStream.newlyBoundedExplainedBytes)+" residual="+std::to_string(stats_.commandStream.unresolvedAfterCommandStream)+" spans="+std::to_string(stats_.commandStream.residualSpansAfterCommandStream));for(const auto&p:commandStreamClosureProvenance_)o.push_back("$"+h21(p.address)+" exact="+(p.exact?"yes":"no")+" bounded="+(p.bounded?"yes":"no")+" proofs="+ids21(p.addressProofIds,"proof#")+" values="+ids21(p.valueProofIds,"value#")+" aliases="+ids21(p.writerAliasRecordIds,"alias#")+" streams="+ids21(p.commandStreamRecordIds,"stream#")+" source="+pcs21(p.sourcePCs)+" :: "+p.note);return o;}

} // namespace pacripper
