// PacRipper maze-topology analysis integration / residual classification
// Created by Jacob Hodgkins

#include "Decompiler.h"

#include <algorithm>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>

namespace pacripper {
namespace {
std::string h22(std::uint16_t v){std::ostringstream o;o<<std::uppercase<<std::hex<<std::setw(4)<<std::setfill('0')<<(unsigned)v;return o.str();}
std::string h822(std::uint8_t v){std::ostringstream o;o<<std::uppercase<<std::hex<<std::setw(2)<<std::setfill('0')<<(unsigned)v;return o.str();}
template<class T>std::string ids22(const std::set<T>&s,const char*p=""){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<p<<v;}o<<"}";return o.str();}
std::string pcs22(const std::set<std::uint16_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<"$"<<h22(v);}o<<"}";return o.str();}
std::string bytes22(const std::set<std::uint8_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<"$"<<h822(v);}o<<"}";return o.str();}
std::string domain22(const AddressLatticeValue&v){std::set<std::uint16_t>d;if(!RootContextAnalysis::completeFiniteDomain(v,d))return"unknown";return pcs22(d);}
bool overlap22(std::uint16_t a0,std::uint16_t a1,std::uint16_t b0,std::uint16_t b1){return a0<b1&&b0<a1;}
}

void Decompiler::buildMazeTopology(){
    mazeTopologyTopologyInputs_.clear();mazeTopologyDirectionCandidates_.clear();mazeTopologyRetryLoopProofs_.clear();mazeTopologyAddressProofs_.clear();mazeTopologyResidualClassification_.clear();mazeTopologyClosureProvenance_.clear();mazeTopologyClosureBytes_.clear();stats_.mazeTopology={};
    if(!analyzer_)return;
    const auto&baseline=!commandStreamClosureBytes_.empty()?commandStreamClosureBytes_:memoryAliasClosureBytes_;mazeTopologyClosureBytes_=baseline;
    const auto result=MazeTopologyAnalysis::analyze(*analyzer_);mazeTopologyTopologyInputs_=result.topologyInputs;mazeTopologyDirectionCandidates_=result.directionCandidates;mazeTopologyRetryLoopProofs_=result.retryLoopProofs;mazeTopologyAddressProofs_=result.addressProofs;

    std::map<std::uint16_t,MazeTopologyClosureProvenanceRecord>prov;
    for(const auto&p:mazeTopologyAddressProofs_){
        if(!MazeTopologyAnalysis::semanticRomClosureEligible(p))continue;
        std::set<std::uint16_t>d;if(!RootContextAnalysis::completeFiniteDomain(p.address,d))continue;const bool exact=d.size()==1;
        for(auto a:d){if(a>=mazeTopologyClosureBytes_.size()||a>=baseline.size()||baseline[a].primary!=RomClosurePrimary::Unresolved)continue;auto&b=mazeTopologyClosureBytes_[a];if(exact)b.staticExactDataUse=true;else b.boundedConsumer=true;b.consumerPCs.insert(p.pc);b.primary=RomClosure::classify(b);auto&v=prov[a];v.address=a;v.exact=v.exact||exact;v.bounded=v.bounded||!exact;v.addressProofIds.insert(p.id);v.retryLoopProofIds.insert(p.retryLoopProofIds.begin(),p.retryLoopProofIds.end());v.topologyInputIds.insert(p.topologyInputIds.begin(),p.topologyInputIds.end());v.sourcePCs.insert(p.pc);v.sourcePCs.insert(p.proofPCs.begin(),p.proofPCs.end());v.note=exact?"exact maze-topology analysis topology/retry-loop ROM address":"bounded maze-topology analysis topology/retry-loop ROM address";}
    }
    for(auto&kv:prov)mazeTopologyClosureProvenance_.push_back(kv.second);

    // Re-inventory the actual maze-topology analysis residual. Classification is deliberately
    // audit-only unless a separate accepted proof changes per-byte closure.
    for(std::size_t i=0;i<mazeTopologyClosureBytes_.size();){
        if(mazeTopologyClosureBytes_[i].primary!=RomClosurePrimary::Unresolved){++i;continue;}
        const std::size_t s=i;while(i<mazeTopologyClosureBytes_.size()&&mazeTopologyClosureBytes_[i].primary==RomClosurePrimary::Unresolved)++i;const std::size_t e=i;
        MazeTopologyResidualClassificationRecord r;r.id=mazeTopologyResidualClassification_.size();r.start=static_cast<std::uint16_t>(s);r.end=static_cast<std::uint16_t>(e);
        if(s<=0x3307&&e>=0x330F){r.kind=MazeTopologyResidualKind::RetryLoopDependent;r.proofPCs={0x291E,0x294D,0x2950,0x2957,0x2959,0x2963,0x32FF,0x3307};r.staticStructuralEvidence=true;r.note="duplicated direction backing bytes remain unresolved because the consumer retry-loop address domain is conditional on the incomplete attract/demo topology lifecycle proof";}
        else if(s==0x3FFE&&e==0x4000){r.kind=MazeTopologyResidualKind::GenuineUnresolved;r.staticStructuralEvidence=false;r.note="final two ROM bytes remain genuinely unresolved; checksum-only or adjacency evidence is insufficient for semantic typing";}
        else{
            bool decoderGap=false,noConsumer=false;
            for(const auto&a:highRomResidualAudit_)if(overlap22(r.start,r.end,a.start,a.end)){
                if(a.categories.count(HighRomAuditCategory::PointerTableGap)||a.categories.count(HighRomAuditCategory::StreamTargetGap)||a.categories.count(HighRomAuditCategory::RecordFieldGap)||a.categories.count(HighRomAuditCategory::DecoderUnreachedPayload)||a.categories.count(HighRomAuditCategory::PossibleSharedObjectOverlap))decoderGap=true;
                if(a.categories.count(HighRomAuditCategory::NoSemanticConsumer))noConsumer=true;
            }
            if(decoderGap){r.kind=MazeTopologyResidualKind::DecoderOrTableGap;r.staticStructuralEvidence=true;r.note="still adjacent/overlapping with source-proven decoder/table/record structures, but no complete semantic extent proof reaches these bytes; classification is research guidance only";}
            else{r.kind=MazeTopologyResidualKind::NoSemanticConsumer;r.staticStructuralEvidence=noConsumer;r.note="no accepted semantic consumer currently reaches this residual span; exhaustive modeled-static negative proof is still absent, so the bytes remain unresolved";}
        }
        r.closesBytes=false;mazeTopologyResidualClassification_.push_back(std::move(r));
    }

    auto&st=stats_.mazeTopology;st.topologyInputs=mazeTopologyTopologyInputs_.size();for(const auto&r:mazeTopologyTopologyInputs_)if(r.topologyComplete)++st.completeTopologyInputs;st.directionCandidateRecords=mazeTopologyDirectionCandidates_.size();for(const auto&r:mazeTopologyDirectionCandidates_)if(r.duplicateBacking)++st.duplicateDirectionRecords;st.retryLoopProofs=mazeTopologyRetryLoopProofs_.size();for(const auto&r:mazeTopologyRetryLoopProofs_)if(r.accepted)++st.acceptedRetryLoopProofs;st.addressProofs=mazeTopologyAddressProofs_.size();for(const auto&p:mazeTopologyAddressProofs_)if(p.accepted)++st.acceptedAddressProofs;st.inheritedBlockers=result.inheritedBlockerPCs.size();st.refinedInheritedBlockers=result.refinedInheritedBlockerPCs.size();st.remainingBlockers=result.remainingBlockerPCs.size();st.residualClassificationRecords=mazeTopologyResidualClassification_.size();st.closureProvenanceRecords=mazeTopologyClosureProvenance_.size();
    for(const auto&r:mazeTopologyResidualClassification_){const std::size_t n=static_cast<std::size_t>(r.end-r.start);switch(r.kind){case MazeTopologyResidualKind::RetryLoopDependent:st.retryLoopDependentResidualBytes+=n;break;case MazeTopologyResidualKind::DecoderOrTableGap:st.decoderOrTableGapResidualBytes+=n;break;case MazeTopologyResidualKind::NoSemanticConsumer:st.noSemanticConsumerResidualBytes+=n;break;case MazeTopologyResidualKind::GenuineUnresolved:st.genuineUnresolvedResidualBytes+=n;break;}}
    bool in=false;for(std::size_t i=0;i<mazeTopologyClosureBytes_.size();++i){const bool u=mazeTopologyClosureBytes_[i].primary==RomClosurePrimary::Unresolved;if(u){++st.unresolvedAfterMazeTopology;if(!in){++st.residualSpansAfterMazeTopology;in=true;}}else in=false;if(i<baseline.size()&&baseline[i].primary==RomClosurePrimary::Unresolved&&!u){if(mazeTopologyClosureBytes_[i].staticExactDataUse)++st.newlyExactExplainedBytes;else ++st.newlyBoundedExplainedBytes;}}st.newlyExplainedBytes=st.newlyExactExplainedBytes+st.newlyBoundedExplainedBytes;
}

std::vector<std::string> Decompiler::mazeTopologyTopologyInputLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis topology input proofs");o.push_back("inputs="+std::to_string(stats_.mazeTopology.topologyInputs)+" complete="+std::to_string(stats_.mazeTopology.completeTopologyInputs));for(const auto&r:mazeTopologyTopologyInputs_)o.push_back("topology#"+std::to_string(r.id)+" kind="+MazeTopologyAnalysis::topologyKindText(r.kind)+" name="+r.name+" callers="+pcs22(r.callerPCs)+" coords="+pcs22(r.coordinateAddresses)+" dirs="+pcs22(r.directionAddresses)+" passable="+std::to_string(r.passableNodes)+" min-degree="+std::to_string(r.minimumPassableDegree)+" deadends="+std::to_string(r.deadEndNodes)+" fixed-low="+bytes22(r.fixedLowCoordinates)+" blocked-neighbor-low="+bytes22(r.blockedNeighborLowCoordinates)+" shape="+(r.sourceShapeProven?"yes":"no")+" complete="+(r.topologyComplete?"yes":"no")+" retry-applicable="+(r.retryExitApplicable?"yes":"no")+" :: "+r.note);return o;}
std::vector<std::string> Decompiler::mazeTopologyDirectionCandidateLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis direction candidate backing records");o.push_back("records="+std::to_string(stats_.mazeTopology.directionCandidateRecords)+" duplicate-backing="+std::to_string(stats_.mazeTopology.duplicateDirectionRecords));for(const auto&r:mazeTopologyDirectionCandidates_)o.push_back("candidate#"+std::to_string(r.id)+" physical-index="+std::to_string(r.physicalRecordIndex)+" semantic-dir="+std::to_string(r.semanticDirection)+" addr=$"+h22(r.address)+" delta=($"+h822(r.deltaLow)+",$"+h822(r.deltaHigh)+") duplicate="+(r.duplicateBacking?"yes":"no")+" byte-exact="+(r.byteExact?"yes":"no")+" :: "+r.note);return o;}
std::vector<std::string> Decompiler::mazeTopologyRetryLoopProofLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis $291E retry-loop proof");o.push_back("proofs="+std::to_string(stats_.mazeTopology.retryLoopProofs)+" accepted="+std::to_string(stats_.mazeTopology.acceptedRetryLoopProofs)+" blockers="+std::to_string(stats_.mazeTopology.remainingBlockers));for(const auto&r:mazeTopologyRetryLoopProofs_)o.push_back("retry#"+std::to_string(r.id)+" routine=$"+h22(r.routine)+" callers="+pcs22(r.callerPCs)+" topology="+ids22(r.topologyInputIds,"topology#")+" candidates="+ids22(r.directionCandidateIds,"candidate#")+" caller-complete="+(r.callerCoverageComplete?"yes":"no")+" modulo="+(r.moduloCycleProven?"yes":"no")+" reverse="+(r.reverseRejectionProven?"yes":"no")+" ix-progress="+(r.ixProgressionProven?"yes":"no")+" passability="+(r.passabilityTestProven?"yes":"no")+" tunnel-gate="+(r.tunnelWrapExclusionProven?"yes":"no")+" duplicate="+(r.duplicateBackingProven?"yes":"no")+" maze-exit="+(r.canonicalMazeExitProven?"yes":"no")+" all-topologies="+(r.allTopologyStatesComplete?"yes":"no")+" accepted="+(r.accepted?"yes":"no")+" missing={"+r.missingStaticFact+"} :: "+r.note);return o;}
std::vector<std::string> Decompiler::mazeTopologyAddressProofLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis conditional/accepted address proofs");o.push_back("proofs="+std::to_string(stats_.mazeTopology.addressProofs)+" accepted="+std::to_string(stats_.mazeTopology.acceptedAddressProofs)+" refined="+std::to_string(stats_.mazeTopology.refinedInheritedBlockers)+" remaining="+std::to_string(stats_.mazeTopology.remainingBlockers));for(const auto&p:mazeTopologyAddressProofs_)o.push_back("proof#"+std::to_string(p.id)+" pc=$"+h22(p.pc)+" operand="+p.operand+" class="+RootContextAnalysis::domainClassText(p.domainClass)+" accepted-domain="+domain22(p.address)+" conditional-domain="+pcs22(p.candidateFiniteDomain)+" conditional="+(p.candidateDomainConditional?"yes":"no")+" accepted="+(p.accepted?"yes":"no")+" retry="+ids22(p.retryLoopProofIds,"retry#")+" topology="+ids22(p.topologyInputIds,"topology#")+" :: "+p.note);return o;}
std::vector<std::string> Decompiler::mazeTopologyResidualClassificationLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis residual static classification");o.push_back("spans="+std::to_string(stats_.mazeTopology.residualClassificationRecords)+" retry-dependent-bytes="+std::to_string(stats_.mazeTopology.retryLoopDependentResidualBytes)+" decoder/table-gap-bytes="+std::to_string(stats_.mazeTopology.decoderOrTableGapResidualBytes)+" no-consumer-bytes="+std::to_string(stats_.mazeTopology.noSemanticConsumerResidualBytes)+" genuine-unresolved-bytes="+std::to_string(stats_.mazeTopology.genuineUnresolvedResidualBytes));for(const auto&r:mazeTopologyResidualClassification_)o.push_back("residual#"+std::to_string(r.id)+" $"+h22(r.start)+"-$"+h22(static_cast<std::uint16_t>(r.end-1))+" len="+std::to_string(r.end-r.start)+" kind="+MazeTopologyAnalysis::residualKindText(r.kind)+" structural="+(r.staticStructuralEvidence?"yes":"no")+" closes="+(r.closesBytes?"yes":"no")+" proof="+pcs22(r.proofPCs)+" :: "+r.note);return o;}
std::vector<std::string> Decompiler::mazeTopologyClosureLines() const{std::vector<std::string>o;if(!ready_)return{"Decompiler model not built."};o.push_back("PacRipper maze-topology analysis topology/retry-loop closure");o.push_back("new="+std::to_string(stats_.mazeTopology.newlyExplainedBytes)+" exact="+std::to_string(stats_.mazeTopology.newlyExactExplainedBytes)+" bounded="+std::to_string(stats_.mazeTopology.newlyBoundedExplainedBytes)+" residual="+std::to_string(stats_.mazeTopology.unresolvedAfterMazeTopology)+" spans="+std::to_string(stats_.mazeTopology.residualSpansAfterMazeTopology));for(const auto&p:mazeTopologyClosureProvenance_)o.push_back("$"+h22(p.address)+" exact="+(p.exact?"yes":"no")+" bounded="+(p.bounded?"yes":"no")+" proofs="+ids22(p.addressProofIds,"proof#")+" retry="+ids22(p.retryLoopProofIds,"retry#")+" topology="+ids22(p.topologyInputIds,"topology#")+" source="+pcs22(p.sourcePCs)+" :: "+p.note);return o;}

} // namespace pacripper
