// PacRipper residual-closure analysis neutral semantic ROM/RAM/state roles and state xrefs
// Created by Jacob Hodgkins

#include "ObjectStateRoles.h"

#include <algorithm>
#include <map>
#include <sstream>
#include <tuple>

namespace pacripper {
namespace {
bool intersects(std::uint16_t a0,std::uint16_t a1,std::uint16_t b0,std::uint16_t b1){return a0<b1&&b0<a1;}
bool readAccess(MemoryAccessKind k){return k==MemoryAccessKind::Read||k==MemoryAccessKind::ReadWrite;}
bool writeAccess(MemoryAccessKind k){return k==MemoryAccessKind::Write||k==MemoryAccessKind::ReadWrite;}
const RoutineRoleSignatureRecord* roleFor(const std::map<std::uint16_t,const RoutineRoleSignatureRecord*>&m,std::uint16_t fn){auto it=m.find(fn);return it==m.end()?nullptr:it->second;}
std::string targetKey(ObjectRoleTargetKind k,std::size_t id){return std::to_string(static_cast<int>(k))+":"+std::to_string(id);}
}

std::string ObjectStateRoles::targetKindText(ObjectRoleTargetKind k){switch(k){case ObjectRoleTargetKind::RomObject:return"rom-object";case ObjectRoleTargetKind::RamObject:return"ram-object";case ObjectRoleTargetKind::RamShape:return"ram-shape";case ObjectRoleTargetKind::RamSchema:return"ram-schema";}return"object";}
std::string ObjectStateRoles::roleText(ObjectStateRoleKind r){switch(r){case ObjectStateRoleKind::RomDataObject:return"rom_data_object";case ObjectStateRoleKind::RomLookupTable:return"rom_lookup_table";case ObjectStateRoleKind::RomPointerTable:return"rom_pointer_table";case ObjectStateRoleKind::RomCommandStream:return"rom_command_stream";case ObjectStateRoleKind::RomRecordTable:return"rom_record_table";case ObjectStateRoleKind::StateStorage:return"state_storage";case ObjectStateRoleKind::StateCounter:return"state_counter";case ObjectStateRoleKind::StateFlagMask:return"state_flag_mask";case ObjectStateRoleKind::StateIndex:return"state_index";case ObjectStateRoleKind::StateTimerLike:return"state_timer_like";case ObjectStateRoleKind::StateCoordinatePair:return"state_coordinate_pair";case ObjectStateRoleKind::StatePointer:return"state_pointer";case ObjectStateRoleKind::VideoState:return"video_state";case ObjectStateRoleKind::InputSample:return"input_sample";case ObjectStateRoleKind::SoundRegisterSource:return"sound_register_source";}return"machine_state";}
std::string ObjectStateRoles::stateXrefTargetText(StateXrefTargetKind k){return k==StateXrefTargetKind::RamObject?"ram-object":"ram-schema";}

bool ObjectStateRoles::rolesConflict(ObjectStateRoleKind a,ObjectStateRoleKind b){
    if(a==b)return false;
    const auto rom=[&](ObjectStateRoleKind r){return r==ObjectStateRoleKind::RomDataObject||r==ObjectStateRoleKind::RomLookupTable||r==ObjectStateRoleKind::RomPointerTable||r==ObjectStateRoleKind::RomCommandStream||r==ObjectStateRoleKind::RomRecordTable;};
    if(rom(a)&&rom(b)&&a!=ObjectStateRoleKind::RomDataObject&&b!=ObjectStateRoleKind::RomDataObject)return true;
    if((a==ObjectStateRoleKind::StateFlagMask&&b==ObjectStateRoleKind::StateCoordinatePair)||(b==ObjectStateRoleKind::StateFlagMask&&a==ObjectStateRoleKind::StateCoordinatePair))return true;
    if((a==ObjectStateRoleKind::StatePointer&&b==ObjectStateRoleKind::StateCoordinatePair)||(b==ObjectStateRoleKind::StatePointer&&a==ObjectStateRoleKind::StateCoordinatePair))return true;
    return false;
}

std::vector<StateXrefRecord> ObjectStateRoles::buildStateXrefs(const std::vector<RamObjectRecord>& ramObjects,const std::vector<RamShapeRecord>& ramShapes,const std::vector<TableSchemaRecord>& schemas,const std::vector<MemoryXrefRecord>& memoryXrefs,const std::vector<TypeEvidenceRecord>& types,const std::vector<RoutineRoleSignatureRecord>& routineRoles,const std::vector<RoutineNavigationRecord>& navigation,const std::map<std::uint16_t,RamAddressUsage>& ramUsage){
    struct Target{StateXrefTargetKind kind;std::size_t id;std::uint16_t start,end;};std::vector<Target> targets;
    for(const auto&r:ramObjects)if(r.staticProof&&!r.dynamicOnly)targets.push_back({StateXrefTargetKind::RamObject,r.id,r.start,r.end});
    std::map<std::size_t,const RamShapeRecord*> shapeById;for(const auto&s:ramShapes)shapeById[s.id]=&s;
    for(const auto&s:schemas)if(s.targetKind==SchemaTargetKind::RamShape&&s.staticProof){auto si=shapeById.find(s.targetId);if(si!=shapeById.end()&&si->second->staticProof)targets.push_back({StateXrefTargetKind::RamSchema,s.id,s.start,s.end});}
    std::map<std::uint16_t,const RoutineRoleSignatureRecord*> roles;for(const auto&r:routineRoles)roles[r.functionEntry]=&r;std::map<std::uint16_t,const RoutineNavigationRecord*> nav;for(const auto&n:navigation)nav[n.functionEntry]=&n;
    std::vector<StateXrefRecord> out;for(const auto&t:targets){StateXrefRecord r;r.id=out.size();r.targetKind=t.kind;r.targetId=t.id;r.start=t.start;r.end=t.end;
        for(const auto&x:memoryXrefs){if(!intersects(t.start,t.end,x.start,x.end))continue;if(x.staticProof&&(x.addressResolution==AddressResolutionKind::ExactStatic||x.addressResolution==AddressResolutionKind::BoundedStatic)){
                const bool definite=x.addressResolution==AddressResolutionKind::ExactStatic;if(readAccess(x.access)){(definite?r.definiteReaderPCs:r.possibleReaderPCs).insert(x.pc);for(auto fn:x.functionOwners)(definite?r.definiteReaderRoutines:r.possibleReaderRoutines).insert(fn);}if(writeAccess(x.access)){(definite?r.definiteWriterPCs:r.possibleWriterPCs).insert(x.pc);for(auto fn:x.functionOwners)(definite?r.definiteWriterRoutines:r.possibleWriterRoutines).insert(fn);r.writeDefinitionIds.insert(x.valueDefinitionIds.begin(),x.valueDefinitionIds.end());r.writeValueOriginPCs.insert(x.valueDefinitionPCs.begin(),x.valueDefinitionPCs.end());}}
        }
        for(const auto&ty:types)if(ty.targetKind==TypeTargetKind::RamRange&&ty.staticProof&&!ty.dynamicOnly&&intersects(t.start,t.end,ty.start,ty.end)){r.typeEvidenceIds.insert(ty.id);if(ty.maskKnown)r.masks.insert(ty.mask);if(ty.rangeMinKnown&&ty.rangeMaxKnown)r.ranges.insert({ty.rangeMin,ty.rangeMax});}
        std::set<std::uint16_t> routines=r.definiteReaderRoutines;routines.insert(r.possibleReaderRoutines.begin(),r.possibleReaderRoutines.end());routines.insert(r.definiteWriterRoutines.begin(),r.definiteWriterRoutines.end());routines.insert(r.possibleWriterRoutines.begin(),r.possibleWriterRoutines.end());for(auto fn:routines){const auto*rr=roleFor(roles,fn);if(rr){r.hardwareCorrelations.insert(rr->definiteHardwareReads.begin(),rr->definiteHardwareReads.end());r.hardwareCorrelations.insert(rr->possibleHardwareReads.begin(),rr->possibleHardwareReads.end());r.hardwareCorrelations.insert(rr->definiteHardwareWrites.begin(),rr->definiteHardwareWrites.end());r.hardwareCorrelations.insert(rr->possibleHardwareWrites.begin(),rr->possibleHardwareWrites.end());}auto ni=nav.find(fn);if(ni!=nav.end()){r.callPathNeighbors.insert(ni->second->callers.begin(),ni->second->callers.end());r.callPathNeighbors.insert(ni->second->callees.begin(),ni->second->callees.end());}}
        for(std::size_t a=t.start;a<t.end;++a){auto ui=ramUsage.find(static_cast<std::uint16_t>(a));if(ui==ramUsage.end())continue;r.dynamicReaderPCs.insert(ui->second.dynamicReaders.begin(),ui->second.dynamicReaders.end());r.dynamicWriterPCs.insert(ui->second.dynamicWriters.begin(),ui->second.dynamicWriters.end());}
        r.dynamicCorroborated=!r.dynamicReaderPCs.empty()||!r.dynamicWriterPCs.empty();r.note="definite xrefs require exact static addresses; bounded static xrefs remain possible; dynamic observations are retained separately";out.push_back(r);
    }return out;
}

void ObjectStateRoles::attachResearchAnnotation(ObjectRoleRecord&r,const std::string&name,const std::string&comment,const std::string&typeHint){r.researcherName=name;r.researcherComment=comment;r.researcherTypeHint=typeHint;}

std::vector<ObjectRoleRecord> ObjectStateRoles::inferRoles(const std::vector<RomObjectRecord>& romObjects,const std::vector<RamObjectRecord>& ramObjects,const std::vector<RamShapeRecord>& ramShapes,const std::vector<TableSchemaRecord>& schemas,const std::vector<TypeEvidenceRecord>& types,const DefUseResult& defUse,const std::vector<IndexedExpressionRecord>& indexedExpressions,const std::map<std::uint16_t,Instruction>& instructions,const std::vector<StateXrefRecord>& stateXrefs,const std::map<std::uint16_t,std::set<std::uint16_t>>& pcOwners,const std::vector<RoutineRoleSignatureRecord>& routineRoles,const SymbolDatabase& symbols){
    (void)pcOwners;
    (void)routineRoles;
    (void)ramShapes;
    std::vector<ObjectRoleRecord> out;
    auto add=[&](ObjectRoleTargetKind tk,std::size_t tid,std::uint16_t start,std::uint16_t end,ObjectStateRoleKind role,bool exact,const std::set<std::uint16_t>&pcs,const std::set<std::size_t>&typeIds,const std::set<std::size_t>&schemaIds,const std::set<std::uint16_t>&routines,const std::set<BoardDeviceKind>&devices,const std::string&summary){ObjectRoleRecord r;r.id=out.size();r.targetKind=tk;r.targetId=tid;r.start=start;r.end=end;r.role=role;r.staticProof=true;r.exact=exact;r.sourcePCs=pcs;r.typeEvidenceIds=typeIds;r.schemaIds=schemaIds;r.routineEntries=routines;r.correlatedDevices=devices;r.evidenceSummary=summary;if(const auto*u=symbols.find(start))attachResearchAnnotation(r,u->name,u->comment,std::string());out.push_back(r);};
    for(const auto&o:romObjects){if(o.dynamicOnly||!(o.exactBoundary||o.boundedBoundary))continue;ObjectStateRoleKind role=ObjectStateRoleKind::RomDataObject;switch(o.kind){case RomObjectKind::ByteLookupTable:role=ObjectStateRoleKind::RomLookupTable;break;case RomObjectKind::WordPointerTable:role=ObjectStateRoleKind::RomPointerTable;break;case RomObjectKind::SequentialStream:role=ObjectStateRoleKind::RomCommandStream;break;case RomObjectKind::RecordTable:role=ObjectStateRoleKind::RomRecordTable;break;default:break;}std::set<std::size_t> schemaIds;for(const auto&s:schemas)if(s.targetKind==SchemaTargetKind::RomObject&&s.targetId==o.id&&s.staticProof)schemaIds.insert(s.id);std::set<std::size_t> typeIds;for(const auto&t:types)if(t.targetKind==TypeTargetKind::RomObject&&t.romObjectId==o.id&&t.staticProof&&!t.dynamicOnly)typeIds.insert(t.id);add(ObjectRoleTargetKind::RomObject,o.id,o.start,o.end,role,o.exactBoundary,o.consumerPCs,typeIds,schemaIds,{}, {},"role follows the statically reconstructed ROM consumer/object kind; no gameplay name is inferred");}
    std::map<std::size_t,const StateXrefRecord*> xrefByRam;for(const auto&x:stateXrefs)if(x.targetKind==StateXrefTargetKind::RamObject)xrefByRam[x.targetId]=&x;
    std::map<std::size_t,const StateXrefRecord*> xrefBySchema;for(const auto&x:stateXrefs)if(x.targetKind==StateXrefTargetKind::RamSchema)xrefBySchema[x.targetId]=&x;
    auto collectType=[&](std::uint16_t start,std::uint16_t end,std::set<std::size_t>&ids,bool&mask,bool&range,bool&pointer){for(const auto&t:types)if(t.targetKind==TypeTargetKind::RamRange&&t.staticProof&&!t.dynamicOnly&&intersects(start,end,t.start,t.end)){ids.insert(t.id);mask=mask||t.role==TypeRoleKind::BitFieldUse||t.role==TypeRoleKind::MaskedUse;range=range||t.role==TypeRoleKind::RangeCheckUse;pointer=pointer||t.role==TypeRoleKind::Pointer16;}};
    auto routineDevices=[&](const StateXrefRecord*x,std::set<std::uint16_t>&routines,std::set<BoardDeviceKind>&devices){if(!x)return;routines=x->definiteReaderRoutines;routines.insert(x->definiteWriterRoutines.begin(),x->definiteWriterRoutines.end());devices=x->hardwareCorrelations;};
    auto isIncDecAt=[&](const std::set<std::uint16_t>&pcs){for(auto pc:pcs){auto i=instructions.find(pc);if(i!=instructions.end()&&(i->second.mnemonic=="INC"||i->second.mnemonic=="DEC"))return true;}return false;};
    auto indexedFromRange=[&](std::uint16_t start,std::uint16_t end){std::set<std::size_t> defs;for(const auto&e:defUse.expressions)if(e.exact&&e.memoryAddressKnown&&e.memoryAddress>=start&&e.memoryAddress<end)defs.insert(e.definitionId);for(const auto&i:indexedExpressions)if(i.staticProof&&i.finiteBounds)for(auto d:i.indexDefinitionIds)if(defs.count(d))return true;return false;};
    for(const auto&o:ramObjects){if(!o.staticProof||o.dynamicOnly)continue;const auto xi=xrefByRam.find(o.id);const StateXrefRecord*x=xi==xrefByRam.end()?nullptr:xi->second;std::set<std::size_t> typeIds;bool mask=false,range=false,pointer=false;collectType(o.start,o.end,typeIds,mask,range,pointer);std::set<std::uint16_t> routines;std::set<BoardDeviceKind> devices;routineDevices(x,routines,devices);std::set<std::uint16_t> pcs=o.sourcePCs;if(x){pcs.insert(x->definiteReaderPCs.begin(),x->definiteReaderPCs.end());pcs.insert(x->definiteWriterPCs.begin(),x->definiteWriterPCs.end());}add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StateStorage,true,pcs,typeIds,{},routines,devices,"statically proven RAM field/object with machine readers/writers; hardware use is correlation metadata only");const bool incdec=x&&isIncDecAt(x->definiteWriterPCs);if(mask)add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StateFlagMask,true,pcs,typeIds,{},routines,devices,"static bit/mask type evidence supports a flag-mask interpretation");if(pointer||o.pointerLike)add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StatePointer,true,pcs,typeIds,{},routines,devices,"16-bit pointer evidence supports a state-pointer role");if(range||indexedFromRange(o.start,o.end))add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StateIndex,true,pcs,typeIds,{},routines,devices,"range/indexed-use evidence supports an index interpretation");if(incdec)add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StateCounter,true,pcs,typeIds,{},routines,devices,"definite static INC/DEC writer evidence supports a counter interpretation");if(incdec&&range)add(ObjectRoleTargetKind::RamObject,o.id,o.start,o.end,ObjectStateRoleKind::StateTimerLike,false,pcs,typeIds,{},routines,devices,"counter plus range/comparison evidence supports a timer-like alternative; gameplay purpose remains unknown");}
    for(const auto&s:schemas){if(s.targetKind!=SchemaTargetKind::RamShape||!s.staticProof)continue;auto xi=xrefBySchema.find(s.id);const StateXrefRecord*x=xi==xrefBySchema.end()?nullptr:xi->second;std::set<std::uint16_t> routines;std::set<BoardDeviceKind> devices;routineDevices(x,routines,devices);std::set<std::uint16_t> pcs=s.sourcePCs;std::set<std::size_t> sid={s.id};add(ObjectRoleTargetKind::RamSchema,s.id,s.start,s.end,ObjectStateRoleKind::StateStorage,s.exactBounds,pcs,{},sid,routines,devices,"finite RAM schema is a statically proven structured state region");}
    // Preserve alternatives explicitly and mark only genuinely incompatible pairs as conflicts.
    std::map<std::string,std::vector<std::size_t>> groups;for(const auto&r:out)groups[targetKey(r.targetKind,r.targetId)].push_back(r.id);for(const auto&g:groups)for(auto id:g.second)for(auto other:g.second)if(id!=other){out[id].alternativeRoleIds.insert(other);if(rolesConflict(out[id].role,out[other].role))out[id].conflictingRoleIds.insert(other);}return out;
}

ObjectStateRoleStats ObjectStateRoles::stats(const std::vector<ObjectRoleRecord>&roles,const std::vector<StateXrefRecord>&xrefs){ObjectStateRoleStats s;s.roleRecords=roles.size();for(const auto&r:roles){if(r.targetKind==ObjectRoleTargetKind::RomObject)++s.romRoleRecords;else ++s.ramRoleRecords;if(!r.conflictingRoleIds.empty())++s.conflictingAlternatives;if(!r.researcherName.empty()||!r.researcherComment.empty()||!r.researcherTypeHint.empty())++s.researcherAnnotatedRecords;}s.stateXrefs=xrefs.size();for(const auto&x:xrefs){if(!x.definiteReaderPCs.empty())++s.stateXrefsWithDefiniteReaders;if(!x.definiteWriterPCs.empty())++s.stateXrefsWithDefiniteWriters;if(x.dynamicCorroborated)++s.dynamicallyCorroboratedStateXrefs;}return s;}

} // namespace pacripper
