// PacRipper structured-expression analysis proof-guided structured expression regions + routine roles
// Created by Jacob Hodgkins

#include "Decompiler.h"

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>

namespace pacripper {
namespace {
std::string h16p13(std::uint16_t v){std::ostringstream o;o<<std::uppercase<<std::hex<<std::setw(4)<<std::setfill('0')<<(unsigned)v;return o.str();}
std::string pcSetP13(const std::set<std::uint16_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<"$"<<h16p13(v);}o<<"}";return o.str();}
std::string sizeSetP13(const std::set<std::size_t>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<v;}o<<"}";return o.str();}
std::string deviceSetP13(const std::set<BoardDeviceKind>&s){std::ostringstream o;o<<"{";std::size_t n=0;for(auto v:s){if(n++)o<<",";o<<HardwareSemantics::deviceText(v);}o<<"}";return o.str();}
std::string factSetP13(const std::set<std::string>&s,std::size_t limit=12){std::ostringstream o;o<<"{";std::size_t n=0;for(const auto&v:s){if(n){o<<",";}if(n++>=limit){o<<"...";break;}o<<v;}o<<"}";return o.str();}
bool relevantRegionP13(RegionKind k){return k==RegionKind::If||k==RegionKind::IfElse||k==RegionKind::While||k==RegionKind::DoWhile;}
bool exactFactP13(const ReachingDefinitionFact&f){return (f.exactDefinition()||f.exactEntryValue())&&!f.includesClobberedUnknown&&!f.ambiguous();}
std::set<std::uint16_t> regionSourceP13(const StructuredRegion&r){return r.sourceBlocks.empty()?r.blocks:r.sourceBlocks;}
std::string indentP13(const std::string&line){std::size_t n=0;while(n<line.size()&&std::isspace(static_cast<unsigned char>(line[n])))++n;return line.substr(0,n);}
bool parseLastPCP13(const std::string&line,std::uint16_t&pc){auto p=line.rfind('$');if(p==std::string::npos||p+5>line.size())return false;unsigned v=0;for(std::size_t i=1;i<=4;++i){char c=line[p+i];unsigned d;if(c>='0'&&c<='9')d=c-'0';else if(c>='A'&&c<='F')d=10+c-'A';else if(c>='a'&&c<='f')d=10+c-'a';else return false;v=(v<<4)|d;}pc=static_cast<std::uint16_t>(v);return true;}
bool containsExactTempP13(const std::string&line,const std::set<std::string>&names){if(line.find("contract-aware value flow typed ")==std::string::npos)return false;for(const auto&n:names){const std::string needle=" "+n+" ";if(line.find(needle)!=std::string::npos)return true;}return false;}
std::string replaceConditionP13(std::string line,const StructuredExpressionRegionRecord&r){if(!r.semanticLifted)return line;std::size_t a=std::string::npos,b=std::string::npos;
    if(r.kind==RegionKind::While&&line.find("if (!(" )!=std::string::npos){a=line.find("if (!(")+6;b=line.find(")) break",a);if(b!=std::string::npos)line.replace(a,b-a,r.renderedCondition);return line;}
    if(r.kind==RegionKind::DoWhile&&line.find("} while (")!=std::string::npos){a=line.find("} while (")+9;b=line.find(");",a);if(b!=std::string::npos)line.replace(a,b-a,r.renderedCondition);return line;}
    if(line.find("if (")!=std::string::npos){a=line.find("if (")+4;b=line.find(") {",a);if(b!=std::string::npos)line.replace(a,b-a,r.renderedCondition);}return line;}
}

void Decompiler::buildStructuredExpression(){
    structuredValueRegions_.clear();temporaryElisions_.clear();callContinuities_.clear();routineRoles_.clear();routineSimilarities_.clear();routineClusters_.clear();routineNavigation_.clear();stats_.structuredExpression={};if(!analyzer_)return;

    std::map<std::uint16_t,std::vector<const UseRecord*>> usesAt;for(const auto&u:defUseResult_.uses)usesAt[u.instructionAddress].push_back(&u);
    std::map<std::uint16_t,std::vector<const TypedValueRecord*>> typedAt;for(const auto&t:typedValues_)if(t.staticProof&&t.exact)typedAt[t.pc].push_back(&t);

    // Reuse the structured-control analysis region tree exactly; only attach expression evidence.
    std::size_t regionId=0;
    for(const auto&sk:structures_){for(const auto*r:StructuredControl::flattenRegions(sk.second.regions)){if(!relevantRegionP13(r->kind))continue;StructuredExpressionRegionInput in;in.functionEntry=sk.first;in.kind=r->kind;in.entry=r->entry;in.conditionPC=r->conditionAddress;in.rawCondition=r->condition;in.staticRegionProof=true;in.sourceBlocks=regionSourceP13(*r);in.provingPCs.insert(r->conditionAddress);
            auto ce=conditionEvidence_.find(r->conditionAddress);if(ce!=conditionEvidence_.end()){
                // StructuredControl already chose the correct taken/not-taken polarity for
                // this region from the semantic CFG edge.  ConditionEvidence::expression
                // is specifically the branch-taken expression, so substituting it here
                // could invert an if/while whose body follows the not-taken edge.  Keep
                // the proven structured-control analysis region polarity and use condition-semantics analysis only as dependency proof.
                in.semanticExpression=r->condition;in.dependenciesExact=ce->second.dependenciesStable&&!ce->second.memoryClobbered&&!ce->second.expression.empty();if(ce->second.producerAddress>=0){const auto p=static_cast<std::uint16_t>(ce->second.producerAddress);in.provingPCs.insert(p);auto ui=usesAt.find(p);if(ui!=usesAt.end())for(const auto*u:ui->second)if(!exactFactP13(u->reaching))in.ambiguousDependencies=true;auto ti=typedAt.find(p);if(ti!=typedAt.end())for(const auto*t:ti->second){in.typedRoles.insert(t->roles.begin(),t->roles.end());in.typedDevices.insert(t->devices.begin(),t->devices.end());}}}
            auto bu=usesAt.find(r->conditionAddress);if(bu!=usesAt.end())for(const auto*u:bu->second)if(!exactFactP13(u->reaching))in.ambiguousDependencies=true;
            structuredValueRegions_.push_back(StructuredValues::makeRegion(regionId++,in));}}

    // Presentation-only temporary elimination chooses the smallest proven region containing the definition.
    std::map<std::size_t,const MachineValueRecord*> valueByDef;for(const auto&v:machineValues_)valueByDef[v.definitionId]=&v;
    std::map<std::size_t,std::vector<const UseRecord*>> usesByDef;for(const auto&u:defUseResult_.uses)for(auto d:u.reaching.definitionIds)usesByDef[d].push_back(&u);
    std::map<std::uint16_t,const HardwareAccessRecord*> hardwareAt;for(const auto&h:hardwareAccesses_)if(h.staticProof)hardwareAt[h.pc]=&h;
    std::set<std::size_t> alreadyElided;std::size_t elideId=0;
    std::vector<const StructuredExpressionRegionRecord*> regionsBySize;for(const auto&r:structuredValueRegions_)regionsBySize.push_back(&r);std::sort(regionsBySize.begin(),regionsBySize.end(),[](const auto*a,const auto*b){if(a->sourceBlocks.size()!=b->sourceBlocks.size())return a->sourceBlocks.size()<b->sourceBlocks.size();return a->id<b->id;});
    for(const auto*r:regionsBySize){for(const auto&d:defUseResult_.definitions){if(alreadyElided.count(d.id)||!d.semanticExact||d.callBoundaryClobber||d.aliasInvalidation)continue;auto pb=instructionToBlock_.find(d.instructionAddress);if(pb==instructionToBlock_.end()||!r->sourceBlocks.count(pb->second))continue;auto vi=valueByDef.find(d.id);if(vi==valueByDef.end())continue;const auto ui=usesByDef.find(d.id);const std::size_t useCount=ui==usesByDef.end()?0:ui->second.size();TemporaryElisionInput in;in.regionId=r->id;in.functionEntry=r->functionEntry;in.definitionId=d.id;in.definitionPC=d.instructionAddress;in.valueName=vi->second->localName;in.staticProof=analyzer_->hasStaticInstructionProof(d.instructionAddress);in.exactSameOriginCopy=vi->second->copyAlias;in.singleConsumerIntermediate=useCount==1;in.allUsesInsideRegion=useCount>0;in.flagsPreserved=true;in.orderPreserved=true;
            if(ui!=usesByDef.end())for(const auto*u:ui->second){in.usePCs.insert(u->instructionAddress);auto ub=instructionToBlock_.find(u->instructionAddress);if(ub==instructionToBlock_.end()||!r->sourceBlocks.count(ub->second)){in.allUsesInsideRegion=false;in.escapesRegion=true;}auto hh=hardwareAt.find(u->instructionAddress);if(hh!=hardwareAt.end()&&(hh->second->volatileAccess||hh->second->sideEffecting))in.volatileOrSideEffecting=true;}
            auto hh=hardwareAt.find(d.instructionAddress);if(hh!=hardwareAt.end()&&(hh->second->volatileAccess||hh->second->sideEffecting))in.volatileOrSideEffecting=true;
            for(const auto&ce:conditionEvidence_)if(ce.second.producerAddress>=0&&static_cast<std::uint16_t>(ce.second.producerAddress)==d.instructionAddress){in.flagsPreserved=false;break;}
            auto ii=analyzer_->instructions().find(d.instructionAddress);if(ii!=analyzer_->instructions().end())in.rawFallback.push_back("$"+h16p13(d.instructionAddress)+" "+ii->second.text());
            if(StructuredValues::canElideTemporary(in)){temporaryElisions_.push_back(StructuredValues::makeTemporaryElision(elideId++,in));alreadyElided.insert(d.id);}}}

    callContinuities_=StructuredValues::buildCallContinuity(callBindings_);
    stats_.structuredExpression.structuredValues=StructuredValues::stats(structuredValueRegions_,temporaryElisions_,callContinuities_);

    // Neutral routine role signatures. Dynamic-only hardware is retained separately and never enters staticFacts/canonicalSignature.
    std::map<std::uint16_t,const RoutineBehaviorRecord*> behaviorByFn;for(const auto&b:routineBehaviors_)behaviorByFn[b.functionEntry]=&b;
    std::map<std::uint16_t,RoutineRoleInput> roleInputs;for(const auto&fk:functions_){RoutineRoleInput r;r.functionEntry=fk.first;roleInputs[fk.first]=r;}
    for(auto&kv:roleInputs){auto bi=behaviorByFn.find(kv.first);if(bi!=behaviorByFn.end()){const auto&b=*bi->second;for(const auto&x:b.machineInputs)(x.certainty==ContractCertainty::Definite?kv.second.definiteInputs:kv.second.possibleInputs).insert(x.reg);for(const auto&x:b.machineOutputs)if(x.certainty==ContractCertainty::Definite)kv.second.definiteOutputs.insert(x.reg);kv.second.definiteRamReads=b.definiteRamReads;kv.second.possibleRamReads=b.possibleRamReads;kv.second.definiteRamWrites=b.definiteRamWrites;kv.second.possibleRamWrites=b.possibleRamWrites;kv.second.readSchemaIds=b.readSchemaIds;kv.second.writeSchemaIds=b.writeSchemaIds;kv.second.definiteHardwareReads=b.definiteHardwareReads;kv.second.possibleHardwareReads=b.possibleHardwareReads;kv.second.definiteHardwareWrites=b.definiteHardwareWrites;kv.second.possibleHardwareWrites=b.possibleHardwareWrites;kv.second.directCallees=b.directCallees;}
        auto si=structures_.find(kv.first);if(si!=structures_.end()){kv.second.loopCount=si->second.loops.size();for(const auto*r:StructuredControl::flattenRegions(si->second.regions)){switch(r->kind){case RegionKind::If:++kv.second.ifCount;break;case RegionKind::IfElse:++kv.second.ifElseCount;break;case RegionKind::While:++kv.second.whileCount;break;case RegionKind::DoWhile:++kv.second.doWhileCount;break;default:break;}}}}
    for(const auto&b:callBindings_){auto ri=roleInputs.find(b.callerFunction);if(ri==roleInputs.end())continue;if(b.hasInputBinding){if(b.inputCertainty==ContractCertainty::Definite)++ri->second.definiteCallInputs;else ++ri->second.possibleCallInputs;}if(b.postValueKind==CallPostValueKind::PreservedInput)++ri->second.preservedCallValues;else if(b.postValueKind==CallPostValueKind::ProducedOutput)++ri->second.returnedCallValues;}
    for(const auto&h:hardwareAccesses_){auto pb=instructionToBlock_.find(h.pc);if(pb==instructionToBlock_.end())continue;auto bb=blocks_.find(pb->second);if(bb==blocks_.end()||bb->second.functionOwners.size()!=1)continue;auto ri=roleInputs.find(*bb->second.functionOwners.begin());if(ri==roleInputs.end())continue;if(h.staticProof&&h.dynamicObserved)ri->second.dynamicCorroborated=true;if(!h.staticProof&&h.dynamicObserved){if(h.access==MemoryAccessKind::Read||h.access==MemoryAccessKind::ReadWrite)ri->second.dynamicOnlyHardwareReads.insert(h.device);if(h.access==MemoryAccessKind::Write||h.access==MemoryAccessKind::ReadWrite)ri->second.dynamicOnlyHardwareWrites.insert(h.device);}}
    for(const auto&kv:roleInputs)routineRoles_.push_back(RoutineRoles::makeSignature(routineRoles_.size(),kv.second));
    for(std::size_t i=0;i<routineRoles_.size();++i)for(std::size_t j=i+1;j<routineRoles_.size();++j)routineSimilarities_.push_back(RoutineRoles::compare(routineRoles_[i],routineRoles_[j]));
    routineClusters_=RoutineRoles::exactClusters(routineRoles_);

    // Routine-centric research navigation; read-only links only.
    std::map<std::uint16_t,const RoutineRoleSignatureRecord*> roleByFn;for(const auto&r:routineRoles_)roleByFn[r.functionEntry]=&r;
    for(const auto&fk:functions_){RoutineNavigationRecord n;n.functionEntry=fk.first;n.callers=fk.second.callers;n.callees=fk.second.callees;auto bi=behaviorByFn.find(fk.first);if(bi!=behaviorByFn.end()){n.schemas=bi->second->readSchemaIds;n.schemas.insert(bi->second->writeSchemaIds.begin(),bi->second->writeSchemaIds.end());n.hardwareDevices=bi->second->definiteHardwareReads;n.hardwareDevices.insert(bi->second->possibleHardwareReads.begin(),bi->second->possibleHardwareReads.end());n.hardwareDevices.insert(bi->second->definiteHardwareWrites.begin(),bi->second->definiteHardwareWrites.end());n.hardwareDevices.insert(bi->second->possibleHardwareWrites.begin(),bi->second->possibleHardwareWrites.end());n.ramAddresses=bi->second->definiteRamReads;n.ramAddresses.insert(bi->second->possibleRamReads.begin(),bi->second->possibleRamReads.end());n.ramAddresses.insert(bi->second->definiteRamWrites.begin(),bi->second->definiteRamWrites.end());n.ramAddresses.insert(bi->second->possibleRamWrites.begin(),bi->second->possibleRamWrites.end());}for(const auto&r:structuredValueRegions_)if(r.functionEntry==fk.first)n.structuredRegionIds.insert(r.id);for(const auto&l:liftedStatements_)if(l.functionEntry==fk.first)n.liftedStatementIds.insert(l.id);for(const auto&s:routineSimilarities_){if(s.first!=fk.first&&s.second!=fk.first)continue;const auto other=s.first==fk.first?s.second:s.first;if(s.kind==RoutineSimilarityKind::ExactSignature)n.similarExact.insert(other);else if(s.kind==RoutineSimilarityKind::CompatibleAdditionalEffects)n.similarCompatible.insert(other);}routineNavigation_.push_back(n);}
    stats_.structuredExpression.roles=RoutineRoles::stats(routineRoles_,routineSimilarities_,routineClusters_,routineNavigation_);
    stats_.structuredExpression.newlyExplainedBytes=0;stats_.structuredExpression.unresolvedAfterStructuredExpression=stats_.contractValue.unresolvedAfterContractValue;
}

std::vector<std::string> Decompiler::structuredValueLines() const{
    if(!ready_) return {"Decompiler model not built."};
    std::vector<std::string> out;out.push_back("PacRipper structured-expression analysis proof-guided structured value pseudocode");out.push_back("structured-control analysis region boundaries are unchanged. Exact condition semantics and contract-aware value flow expressions annotate them; synthetic temporaries are suppressed only from this presentation. Raw statements remain.");{std::ostringstream s;s<<"regions="<<stats_.structuredExpression.structuredValues.regions<<" exact-conditions="<<stats_.structuredExpression.structuredValues.exactSemanticConditions<<" raw-condition-fallback="<<stats_.structuredExpression.structuredValues.rawFallbackConditions<<" presentation-temp-elisions="<<stats_.structuredExpression.structuredValues.temporaryElisions<<" call-continuities="<<stats_.structuredExpression.structuredValues.callContinuities;out.push_back(s.str());}out.push_back("");
    std::set<std::string> hidden;for(const auto&e:temporaryElisions_)hidden.insert(e.valueName);std::map<std::uint16_t,std::vector<const StructuredExpressionRegionRecord*>> regionAt;for(const auto&r:structuredValueRegions_)regionAt[r.conditionPC].push_back(&r);std::map<std::uint16_t,std::vector<const CallContinuityRecord*>> callAt;for(const auto&c:callContinuities_)callAt[c.callPC].push_back(&c);
    auto base=typedPseudocodeLines();for(auto line:base){if(containsExactTempP13(line,hidden))continue;std::uint16_t pc=0;if(parseLastPCP13(line,pc)){auto ci=callAt.find(pc);if(ci!=callAt.end()){const auto ind=indentP13(line);for(const auto*c:ci->second)out.push_back(ind+"// structured-expression analysis exact call continuity: "+c->reg+" -> "+c->postValueName+" ["+(c->preserved?"proven-preserved":"definite-return-output")+"]");}}
        for(const auto&kv:regionAt){const std::string proof="$"+h16p13(kv.first);if(line.find(proof)==std::string::npos)continue;if(line.find("if (")==std::string::npos&&line.find("while (")==std::string::npos&&line.find("exit test")==std::string::npos)continue;const auto ind=indentP13(line);for(const auto*r:kv.second){out.push_back(ind+"// structured-expression analysis region#"+std::to_string(r->id)+" "+StructuredControl::regionKindText(r->kind)+" source-blocks="+pcSetP13(r->sourceBlocks)+" proving="+pcSetP13(r->provingPCs)+(r->semanticLifted?" [exact semantic condition]":" [raw condition retained]"));line=replaceConditionP13(line,*r);}}
        out.push_back(line);}return out;
}

std::vector<std::string> Decompiler::routineRoleLines() const{std::vector<std::string>o;if(!ready_)return {"Decompiler model not built."};o.push_back("PacRipper structured-expression analysis neutral routine role signatures");o.push_back("Labels are disposable summaries of explicit machine facts. Dynamic-only effects never enter the static signature.");o.push_back("signatures="+std::to_string(stats_.structuredExpression.roles.signatures)+" dynamic-corroborated="+std::to_string(stats_.structuredExpression.roles.dynamicallyCorroborated)+" dynamic-only-effect-signatures="+std::to_string(stats_.structuredExpression.roles.signaturesWithDynamicOnlyEffects));o.push_back("");for(const auto&r:routineRoles_){o.push_back("$"+h16p13(r.functionEntry)+" "+r.neutralLabel+" signature-facts="+std::to_string(r.staticFacts.size())+(r.dynamicCorroborated?" [dynamic-corroborated]":""));o.push_back("  static="+factSetP13(r.staticFacts));if(!r.dynamicOnlyFacts.empty())o.push_back("  dynamic-only="+factSetP13(r.dynamicOnlyFacts));}return o;}

std::vector<std::string> Decompiler::routineClusterLines() const{std::vector<std::string>o;if(!ready_)return {"Decompiler model not built."};o.push_back("PacRipper structured-expression analysis similar-routine clustering");o.push_back("Exact/compatible similarity is a navigation aid only; it is not gameplay-purpose proof.");o.push_back("exact-clusters="+std::to_string(stats_.structuredExpression.roles.exactClusters)+" clustered-routines="+std::to_string(stats_.structuredExpression.roles.exactClusteredRoutines)+" compatible-pairs="+std::to_string(stats_.structuredExpression.roles.compatiblePairs)+" materially-different-pairs="+std::to_string(stats_.structuredExpression.roles.materiallyDifferentPairs));o.push_back("");for(const auto&c:routineClusters_){std::ostringstream s;s<<"cluster#"<<c.id<<" "<<RoutineRoles::similarityText(c.kind)<<" members={";for(std::size_t i=0;i<c.members.size();++i){if(i)s<<",";s<<"$"<<h16p13(c.members[i]);}s<<"} shared="<<factSetP13(c.sharedFacts);o.push_back(s.str());}for(const auto&s:routineSimilarities_)if(s.kind==RoutineSimilarityKind::CompatibleAdditionalEffects)o.push_back("$"+h16p13(s.first)+" <-> $"+h16p13(s.second)+" compatible shared="+factSetP13(s.sharedFacts,8)+" first-only="+factSetP13(s.firstOnlyFacts,5)+" second-only="+factSetP13(s.secondOnlyFacts,5));return o;}

std::vector<std::string> Decompiler::routineNavigationLines() const{std::vector<std::string>o;if(!ready_)return {"Decompiler model not built."};o.push_back("PacRipper structured-expression analysis routine research navigation index");o.push_back("Navigation links do not change CFG ownership, function boundaries or proof confidence.");o.push_back("records="+std::to_string(stats_.structuredExpression.roles.navigationRecords));o.push_back("");for(const auto&n:routineNavigation_){o.push_back("function $"+h16p13(n.functionEntry)+" callers="+pcSetP13(n.callers)+" callees="+pcSetP13(n.callees));o.push_back("  schemas="+sizeSetP13(n.schemas)+" hardware="+deviceSetP13(n.hardwareDevices)+" RAM-addresses="+std::to_string(n.ramAddresses.size())+" regions="+sizeSetP13(n.structuredRegionIds)+" lifts="+sizeSetP13(n.liftedStatementIds));if(!n.similarExact.empty())o.push_back("  exact-similar="+pcSetP13(n.similarExact));if(!n.similarCompatible.empty())o.push_back("  compatible-similar="+pcSetP13(n.similarCompatible));}return o;}

} // namespace pacripper
